config/routes.rb
Lbc::Application.routes.draw do
  get "links/fetch"

  get 'login' => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'

  get 'signup' => 'users#new', :as => 'signup'

  resources :users

  resources :searches do
    get :bookmarks, on: :collection
    get :likes, on: :collection
    get :recommendations, on: :collection

    get :results, on: :member
    get 'results/page/:page', :action => :results, :on => :member

    get :statistics, on: :member
    get :run, on: :member
    put :share, on: :member

    resources :links do
      get :fetch, on: :member

      get :like, on: :member
      get :dislike, on: :member

      get :bookmark, on: :member
      get :remove_bookmark, on: :member

      get :hide, on: :member
    end
  end

  resources :sessions

  root :to => 'high_voltage/pages#show', id: 'home'
end

app/views/shared/_sidebar.html.haml
%ul
  %li
    %h1
      = link_to "LBC", root_url
  - if logged_in?
    %li
      = link_to "New Search", new_search_path, class: 'btn btn-primary'
    %li
      = link_to "Search List", searches_path, class: 'btn'
    %li
      = link_to "Bookmarks", bookmarks_searches_path, class: 'btn'
    %li
      = link_to "Likes", likes_searches_path, class: 'btn'
    %li
      = link_to "Recommendations", recommendations_searches_path, class: 'btn'
    %li
      = link_to "Logout", logout_path, class: 'btn'
  - else
    %li
      = link_to "Login", login_path, class: 'btn btn-primary'
    %li
      = link_to "Signup", signup_path, class: 'btn'