config/routes.rb
Lbc::Application.routes.draw do
  get "links/fetch"

  get 'login' => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'

  get 'signup' => 'users#new', :as => 'signup'

  resources :users

  resources :searches do
    get :bookmarks, on: :collection
    get :likes, on: :collection
    get :recommendations, on: :collection

    get :results, on: :member
    get 'results/page/:page', :action => :results, :on => :member

    get :statistics, on: :member
    get :run, on: :member
    put :share, on: :member

    resources :links do
      get :fetch, on: :member

      get :like, on: :member
      get :dislike, on: :member

      get :bookmark, on: :member
      get :remove_bookmark, on: :member

      get :hide, on: :member
    end
  end

  resources :sessions

  root :to => 'high_voltage/pages#show', id: 'home'
end

app/models/search.rb
class SearchPage
  def initialize(response, options = {})
    @response = response
    @body = response.body
    @status = response.status
  end

=begin
  def save_links
    links do |attributes|
      link = Link.new(attributes)
      link.upsert

      yield link if block_given?
    end
  end
=end

  def links
    return unless success? and body

    doc = Nokogiri::HTML(@body)
    
    links = []

    doc.css('div.list-lbc a').each do |a|
      link = {
        :url => a['href'],
        :title => a.css('div.title').first.content.strip
      }

      link[:ad_id] = link[:url][/^http:\/\/www.leboncoin.fr\/locations\/(\d+).*/,1]
      links << link
      yield link if block_given?
    end

    links
  end

  def status
    @status
  end

  def body
    @body
  end

  def success?
    @status == 200
  end
end

class Search
  include Mongoid::Document
  include APIConnection

  extend Enumerize

  field :name, type: String

  field :rent_min, type: Integer
  field :rent_max, type: Integer

  field :area_min, type: Integer
  field :area_max, type: Integer

  field :rooms_min, type: Integer
  field :rooms_max, type: Integer

  field :misc
  enumerize :misc, in: [:house, :flat], multiple: true

  def bip_misc
    misc.to_a * ', '
  end

  field :furniture, type: Boolean

  field :location, type: String

  field :schedule
  enumerize :schedule, in: ['30 minutes'], default: '30 minutes'

  field :last_run, type: DateTime

  belongs_to :user
  has_and_belongs_to_many :users

  def shared_with?(user)
    user = User.find(id) unless user.is_a? User
    user == self.user || !users.find(user).nil?
  rescue Mongoid::Errors::DocumentNotFound
    false
  end

  has_many :links

  def scheduled_at
    Searches30MinutesJob.job.run_at if scheduled?
  end

  def scheduled?
    Searches30MinutesJob.scheduled?
  end

  %w(price surface).each do |criteria|
    define_method "average_#{criteria}" do
      links.avg("details.#{criteria}".to_sym)
    end
    
    define_method "max_#{criteria}" do
      links.max("details.#{criteria}".to_sym)
    end

    define_method "min_#{criteria}" do
      links.min("details.#{criteria}".to_sym)
    end
  end

  CATEGORY = {
    :rents => '12'
  }

  MISC = {
    :house => '1',
    :flat => '2',
    :plot => '3',
    :parking => '4',
    :other => '5',
  }

  ATTR_TABLE = {
    :category => 'c',
    :rent_min => 'mrs',
    :rent_max => 'mre',
    :area_min => 'sqs',
    :area_max => 'sqe',
    :rooms_min => 'ros',
    :rooms_max => 'roe',
    :misc => 'ret',
    :furnitures => 'furn',
    :location => 'location'
  }

  def to_search
    ret = {
      'f' => 'a',
      'c' => '10'
    }

    ATTR_TABLE.each do |k, attribute|
      v = attributes[k.to_s]

      if v
        attribute = ATTR_TABLE[k.to_sym]

        case k
        when :category
          ret[attribute] = CATTEGORY[v]
        when :misc
          if v.is_a? Array
            #ret[attribute] = []
            v.each do |value|
              #ret[attribute].push MISC[value]
            end
          end
        when :furnitures
          ret[attribute] = v === true ? 1 : 2
        else
          ret[attribute] = v
        end
      end
    end
    ret
  end

  def search_page
    res = self.connection.get do |req|
      req.url '/locations/offres/nord_pas_de_calais/'
      req.params = to_search
    end

    SearchPage.new res
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_filter :require_login

  load_and_authorize_resource

  def index
  end

  def results
    @search = Search.find(params[:id])
    @results = @search.links.desc(:id).page params[:page]
  end

  def bookmarks
    @bookmarks = Link.where(:id.in => current_user.bookmarked_link_ids).desc(:id).page params[:page]
    Ramon.log("Test")
  end

  def likes
    @likes = Link.where(:id.in => current_user.liked_link_ids).desc(:id).page params[:page]
  end

  def recommendations
    @recommendations = current_user.recommended_links
    @similar_raters = current_user.similar_raters
  end

  def statistics
    @search = Search.find params[:id]
    authorize!(:read, @search || Search)
  end
  
  def show
  end

  def new
  end

  def create
    @search.user = current_user
    if @search.save
      redirect_to @search
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @search.update_attributes params[:search]
      respond_to do |format|
        format.html { redirect_to @search }
        format.json { render :json => @search }
      end
    else
      respond_to do |format|
        format.html { render :edit }
        format.json { render :json => @search }
      end
    end
  end

  def run
    @search = Search.find params[:id]
    authorize!(:run, @search || Search)

    Delayed::Job.enqueue SearchJob.new(@search.id) if @search

    redirect_to searches_url
  end

  def share
    @search = Search.find params[:id]
    authorize!(:share, @search || Search)

    user = User.find_by_email params[:user][:email]

    if user
      @search.users << user
    end

    redirect_to @search
  end
end

app/views/searches/_form.html.haml
= semantic_form_for @search do |f|
  = f.inputs do
    = f.input :name

  = f.inputs "Parameters" do
    = f.input :rent_min, as: :number
    = f.input :rent_max, as: :number

    = f.input :area_min, as: :number
    = f.input :area_max, as: :number

    = f.input :rooms_min, as: :number
    = f.input :rooms_max, as: :number

    = f.input :misc

    = f.input :furniture, as: :boolean

    = f.input :location

  = f.inputs "Schedule" do
    = f.input :schedule

  = f.actions do
    = f.action :submit
    = f.action :cancel

app/views/searches/_results.html.haml
= paginate results

- results.each do |link|
  .result{id: dom_id(link)}
    .title
      %h4 #{link.title} / #{link.ad_id}
    - unless link.details.nil?
      .details
        %p
          Price: #{link.details.price_string}
          Surface: #{link.details.surface}
          City: #{link.details.city}
          ZipCode: #{link.details.zipcode}
          Furnitures: #{link.details.furnitures}
          Energy Class: #{link.details.energy_class}
          GES: #{link.details.ges}
    .insights
      %p
        Likes: 
        %span.js-likes= link.liked_by_count
        Dislikes: 
        %span.js-dislikes= link.disliked_by_count
    .actions
      %p
        = link_to "Visit", link.url, class: 'original-url'
        \-
        %span.js-like{class: current_user.likes?(link) ? 'hide' : '' }
          = link_to "Like", like_search_link_path(link.search, link), class: 'like js-like', remote: true
          \-
        %span.js-dislike{class: current_user.dislikes?(link) ? 'hide' : '' }
          = link_to "Dislike", dislike_search_link_path(link.search, link), class: 'dislike js-dislike', remote: true
          \-
        %span.js-bookmark{class: current_user.bookmarks?(link) ? 'hide' : '' }
          = link_to "Bookmark", bookmark_search_link_path(link.search, link), class: 'bookmark js-bookmark', remote: true
          \-
        %span.js-remove-bookmark{class: current_user.bookmarks?(link) ? '' : 'hide' }
          = link_to "Remove from bookmarks", remove_bookmark_search_link_path(link.search, link), class: 'remove-bookmark js-remove-bookmark', remote: true
          \-
        %span.js-hide{class: current_user.hides?(link) ? 'hide' : '' }
          = link_to "Hide", hide_search_link_path(link.search, link), class: 'js-hide', remote: true
        \-
        - if can? :manage, link
          = link_to "Fetch", fetch_search_link_path(link.search, link), class: 'fetch js-fetch', remote: true
    .description
      .short
        %p= link.details.description[0..500]
      .long
        %p= link.details.description

= paginate results

:javascript

app/views/searches/bookmarks.html.haml
%h3 Bookmarks

= render :partial => 'results', locals: { results: @bookmarks }

app/views/searches/edit.html.haml
%h1
  Edit Search

= render :partial => 'form'

app/views/searches/index.html.haml
- @searches.each do |search|
  .search{id: dom_id(search)}
    .title
      %h2= search.name
    .parameters
      .rent
        Rent: 
        = best_in_place search, :rent_min, html_attrs: { class: 'span1' }, path: search, type: :input 
        \- 
        = best_in_place search, :rent_max, html_attrs: { class: 'span1' }, path: search, type: :input
      .area
        Area: 
        = best_in_place search, :area_min, html_attrs: { class: 'span1' }, path: search, type: :input 
        \- 
        = best_in_place search, :area_max, html_attrs: { class: 'span1' }, path: search, type: :input
      .rooms
        Rooms: 
        = best_in_place search, :rooms_min, html_attrs: { class: 'span1' }, path: search, type: :input
        \- 
        = best_in_place search, :rooms_max, html_attrs: { class: 'span1' }, path: search, type: :input
      .misc
        Misc: 
        = search.bip_misc
      .location
        Location: 
        = best_in_place search, :location, html_attrs: { class: 'span2' }, path: search, type: :input
    %hr
    - if search.links.any? and search.links.first.details
      .insights
        .price
          Average Price: #{number_to_currency search.average_price}
          %br
          Max Price: #{number_to_currency search.max_price}
          %br
          Min Price: #{number_to_currency search.min_price}
        .surface
          Average Surface: #{search.average_surface.round(2)}
          %br
          Max Surface: #{search.max_surface}
          %br
          Min Surface: #{search.min_surface}
      %hr
    .actions
      .schedule
        %h3 Schedule
        Interval:
        = best_in_place search, :schedule, html_attrs: { class: 'bip' }, path: search, type: :select
        - if search.scheduled?
          %br
          Next run in 
          = distance_of_time_in_words_to_now search.scheduled_at
        - unless search.last_run.nil?
          %br
          Last run: 
          = l(search.last_run, format: :default)
        - if can? :manage, search
          %p
            = link_to "Run", run_search_path(search)
            = link_to "Edit", edit_search_path(search)
      .sharing
        %h3 Sharing
        Shared with #{search.users.collect(&:username).join(', ')}.
        - if can? :share, search
          = semantic_form_for User.new, url: share_search_url(search), method: :put do |f|
            = f.inputs :email
            %br
            = f.actions do
              = f.action :submit
      .misc
        = link_to "Browse Results", results_search_path(search), class: 'btn btn-primary'
        = link_to "View Statistics", statistics_search_path(search), class: 'btn'

app/views/searches/likes.html.haml
%h3 Likes

= render :partial => 'results', locals: { results: @likes }

app/views/searches/new.html.haml
%h1
  New Search

= render :partial => 'form'

app/views/searches/recommendations.html.haml
%h3 Recommendations

- @similar_raters.each do |rater|
  = debug rater

- if @recommendations.any?
  = render :partial => 'results', locals: { results: @recommendations }

app/views/searches/results.html.haml
%h3 Latest Results

= render :partial => 'results', locals: { results: @results }